create schema if not exists public;

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  name text not null,
  document text,
  phone text,
  email text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists clients_document_unique_idx
  on public.clients (document)
  where document is not null;

create table if not exists public.machines (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null,
  identifier text,
  brand_model text,
  status text not null default 'available'
    check (status in ('available', 'allocated', 'under_maintenance', 'inactive')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists machines_identifier_unique_idx
  on public.machines (identifier)
  where identifier is not null;

create table if not exists public.operators (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  role text,
  is_active boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients (id) on delete restrict,
  name text not null,
  location text,
  start_date date,
  end_date date,
  status text not null default 'planned'
    check (status in ('planned', 'active', 'completed', 'canceled')),
  contract_amount numeric,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists projects_client_id_idx on public.projects (client_id);
create index if not exists projects_status_idx on public.projects (status);
create index if not exists projects_start_date_idx on public.projects (start_date);
create index if not exists projects_end_date_idx on public.projects (end_date);

create table if not exists public.daily_logs (
  id bigint generated by default as identity primary key,
  date date not null,
  project_id bigint not null references public.projects (id) on delete restrict,
  machine_id bigint references public.machines (id) on delete set null,
  operator_id bigint references public.operators (id) on delete set null,
  hours_worked numeric not null,
  work_description text,
  fuel_quantity numeric,
  downtime_notes text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists daily_logs_project_id_idx on public.daily_logs (project_id);
create index if not exists daily_logs_machine_id_idx on public.daily_logs (machine_id);
create index if not exists daily_logs_operator_id_idx on public.daily_logs (operator_id);
create index if not exists daily_logs_date_idx on public.daily_logs (date);

create table if not exists public.project_costs (
  id bigint generated by default as identity primary key,
  date date not null,
  project_id bigint not null references public.projects (id) on delete restrict,
  machine_id bigint references public.machines (id) on delete set null,
  operator_id bigint references public.operators (id) on delete set null,
  category text not null
    check (category in ('fuel', 'labor', 'maintenance', 'transport', 'outsourced', 'miscellaneous')),
  description text not null,
  amount numeric not null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists project_costs_project_id_idx on public.project_costs (project_id);
create index if not exists project_costs_machine_id_idx on public.project_costs (machine_id);
create index if not exists project_costs_operator_id_idx on public.project_costs (operator_id);
create index if not exists project_costs_date_idx on public.project_costs (date);
create index if not exists project_costs_category_idx on public.project_costs (category);

create table if not exists public.project_revenues (
  id bigint generated by default as identity primary key,
  date date not null,
  project_id bigint not null references public.projects (id) on delete restrict,
  description text not null,
  amount numeric not null,
  status text not null default 'planned'
    check (status in ('planned', 'billed', 'received')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists project_revenues_project_id_idx on public.project_revenues (project_id);
create index if not exists project_revenues_date_idx on public.project_revenues (date);
create index if not exists project_revenues_status_idx on public.project_revenues (status);
